name: Unit Tests

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
        
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm i --frozen-lockfile

    - name: Build projects
      run: pnpm build

    - name: Run tests
      run: pnpm test